[package]
name = "bagel-rs"
version = "0.1.0"
authors = ["Brandon Smith <mail@brandonsmith.ninja>"]
edition = "2018"

[dependencies]
chumsky = "0.8.0"
ariadne = "0.1.5"
lazy_static = "1.4.0"
Boa = "0.13.0"